title: Your awesome title
author: Gregg Grose
email: gregg.grose@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gregg Grose GitHub Blog

# social links
twitter_username: GreggGrose # DO NOT include the @ character, or else the build will fail!
github_username:  gregggrose # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
